"""Analyst report generation: grounded LLM narrative with template fallback.

The LLM is a *narrator of computed numbers*, never a source: the system
prompt forbids any claim not present in the facts JSON, requires figures to
be quoted, and demands honest caveats (synthetic data, CV-derived events).
When no provider is available (or the call fails) the deterministic template
produces a structured, data-complete report from the same facts — so the
pipeline never blocks on an API. A metrics appendix is always attached, making
every narrative claim auditable against ``facts.json``.
"""

from __future__ import annotations

import json
import logging

from pitchiq.config import ReportConfig
from pitchiq.report import llm as llm_mod

log = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a professional football match analyst writing for a \
coaching staff. You are given a JSON object of computed metrics from an automated \
tracking system — these numbers are your ONLY source of truth.

Hard rules:
1. Every quantitative claim must come from the JSON, with the number quoted.
2. Never invent events, scores, player names, or context not in the JSON.
3. Refer to players exactly as labelled in the JSON (e.g. "#7 (Crimson City)").
4. If the data says the match is synthetic (match.is_synthetic), add one short \
italic note at the top saying this is a simulated demonstration match.
5. Where the data is thin or a metric is missing, say so rather than guessing.
6. Calibrate your confidence to data_quality. When data_quality.overall is \
"high", write confident, concrete analyst prose — no hedging filler. When it is \
"medium" or "low", every ball-dependent claim (possession, passes, xT, PPDA, \
pressing) must carry a brief hedge quoting the relevant coverage number from \
data_quality (e.g. "possession roughly 60/40 — low confidence, ball observed in \
only 41% of frames"). Never present a low-confidence number as settled fact.
7. No bullet spam.

Structure (markdown, ## headings):
## Executive Summary — 3-4 sentences: who controlled what, and how. End with \
one Data Confidence sentence stating data_quality.overall and the single \
biggest caveat from data_quality.notes (or that positions are ground-truth \
exact, if so).
## Tactical Narrative — possession/territory/tilt, formations and in/out-of-\
possession shape morphs, pressing (PPDA, press height) and how the teams' \
approaches interacted. This is the core section.
## Key Players — 3-5 players with the metrics that make them stand out \
(threat creation, physical output, network centrality, discovered role).
## Defensive Schemes — marking analysis: man/zonal/hybrid per team with scores, \
notable marking pairs, block heights.
## Watch-outs & Data Notes — role/position mismatches worth a coach's attention, \
plus honest limitations of the automated data."""


def build_report(facts: dict, cfg: ReportConfig) -> tuple[str, str]:
    """Returns (markdown_report, generator_used: 'gemini'|'anthropic'|'template')."""
    provider = llm_mod.resolve_provider(cfg.llm)
    if provider != "none":
        user = (
            "Computed match metrics JSON:\n\n```json\n"
            + json.dumps(facts, indent=1, default=str)[:24000]
            + "\n```\n\nWrite the report now."
        )
        text = llm_mod.generate(SYSTEM_PROMPT, user, cfg.llm)
        if text and len(text) > 400:
            return _finalise(text, facts), provider
        log.warning("LLM report failed/short — using template fallback")
    return _finalise(template_report(facts), facts), "template"


def _finalise(body: str, facts: dict) -> str:
    return body.rstrip() + "\n\n" + _metrics_appendix(facts)


def _metrics_appendix(facts: dict) -> str:
    keep = ["possession", "field_tilt", "ppda", "pitch_control", "team_distance_m",
            "line_breaking", "events", "data_quality"]
    lines = ["## Metrics Appendix", "",
             "Auto-generated from `facts.json`; every figure above traces here.", ""]
    for k in keep:
        if k in facts and facts[k]:
            lines.append(f"- **{k}**: `{json.dumps(facts[k], default=str)[:500]}`")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ template
def template_report(facts: dict) -> str:
    """Deterministic analyst report — same facts, rule-based prose."""
    t = facts.get("match", {}).get("teams", {"home": "Home", "away": "Away"})
    h, a = t.get("home", "Home"), t.get("away", "Away")
    parts: list[str] = [f"# Match Report — {h} vs {a}", ""]
    if facts.get("match", {}).get("is_synthetic"):
        parts.append("*Simulated demonstration match generated by the PitchIQ engine.*\n")

    # executive summary
    share = facts.get("possession", {}).get("share", {})
    hs = share.get("home", 0.5)
    tilt = facts.get("field_tilt", {}).get("tilt_home")
    ppda = facts.get("ppda", {})
    parts.append("## Executive Summary")
    dom = h if hs >= 0.5 else a
    parts.append(
        f"{dom} controlled the ball ({100 * max(hs, 1 - hs):.0f}% possession"
        + (f", field tilt {tilt:.2f} in favour of {h if tilt and tilt > 0.5 else a}"
           if tilt is not None else "") + "). "
        + _ppda_sentence(ppda, h, a))
    dq = facts.get("data_quality", {})
    if dq:
        conf_sentence = f"Data confidence: **{dq.get('overall', '?')}**."
        if dq.get("notes"):
            conf_sentence += f" {dq['notes'][0]}"
        parts.append(conf_sentence)
    parts.append("")

    # tactical narrative
    parts.append("## Tactical Narrative")
    forms = facts.get("formations", {})
    for key, name in (("home", h), ("away", a)):
        f = forms.get(key, {})
        ip = f.get("in_possession", {})
        op = f.get("out_possession", {})
        if ip or op:
            morph = f.get("shape_morph") or ""
            parts.append(
                f"**{name}** set up in a {ip.get('formation', '?')} with the ball"
                f" (width {ip.get('avg_width_m', '?')} m) and a "
                f"{op.get('formation', '?')} without it"
                + (f" — {morph}." if morph else "."))
        blk = facts.get("shape", {}).get(key, {})
        if blk.get("block_label"):
            oop = blk.get("out_possession", {})
            parts.append(
                f"Off the ball they defended in a {blk['block_label']} "
                f"(defensive line {oop.get('def_line_height_m', '?')} m from goal, "
                f"depth {oop.get('depth_m', '?')} m).")
    press = facts.get("pressing", {})
    for key, name in (("home", h), ("away", a)):
        p = press.get(key, {})
        if p.get("pressures"):
            parts.append(
                f"{name} registered {p['pressures']} pressures "
                f"({p.get('pressures_per_min', '?')}/min), average press height "
                f"{p.get('press_height_mean_m', '?')} m, converting "
                f"{100 * p.get('press_to_turnover_rate', 0):.0f}% into turnovers within 3 s.")
    lb = facts.get("line_breaking", {})
    if lb.get("total"):
        parts.append(f"Line-breaking passes: {lb['total']} "
                     f"({json.dumps(lb.get('by_team', {}))}).")
    parts.append("")

    # key players
    parts.append("## Key Players")
    for r in facts.get("expected_threat", {}).get("top_players", [])[:3]:
        parts.append(f"- {r['player']} created the most threat "
                     f"(xT +{r['xt_created']:.3f} over {r['n_moves']} moves).")
    for r in facts.get("physical", {}).get("top_distance_per_min", [])[:2]:
        parts.append(f"- {r['player']} covered {r['value_m_per_min']:.0f} m/min "
                     f"with {r['sprints']} sprints.")
    for team, net in facts.get("pass_network", {}).items():
        if net.get("most_central_player"):
            parts.append(f"- {net['most_central_player']} was {t.get(team, team)}'s "
                         f"passing hub (highest betweenness centrality).")
    parts.append("")

    # defensive schemes
    parts.append("## Defensive Schemes")
    for key, name in (("home", h), ("away", a)):
        m = facts.get("marking", {}).get(key, {})
        if m:
            parts.append(f"**{name}**: {m.get('scheme', '?')} "
                         f"(man-score {m.get('man_score', '?')}).")
            for pair in m.get("pairs", [])[:4]:
                parts.append(f"  - {pair['defender']} marked {pair['marks']} "
                             f"({100 * pair['share']:.0f}% of defensive samples).")
    parts.append("")

    # watch-outs
    parts.append("## Watch-outs & Data Notes")
    for mm in facts.get("roles", {}).get("nominal_vs_actual", [])[:5]:
        parts.append(f"- {mm['player']} is nominally a {mm['nominal']} but plays as a "
                     f"{mm['discovered']}.")
    parts.append("- Events (passes/turnovers) are derived from tracking, not a manual "
                 "event feed; ball-dependent metrics inherit ball-tracking noise.")
    for note in facts.get("data_quality", {}).get("notes", []):
        parts.append(f"- {note}")
    if facts.get("match", {}).get("is_synthetic"):
        parts.append("- Synthetic match: player behaviour is simulator-generated.")
    return "\n".join(parts) + "\n"


def _ppda_sentence(ppda: dict, h: str, a: str) -> str:
    try:
        hp = ppda.get("home", {}).get("ppda")
        ap = ppda.get("away", {}).get("ppda")
        if hp is None or ap is None:
            return ""
        aggr = h if hp < ap else a
        return f"The more aggressive press came from {aggr} (PPDA {min(hp, ap):.1f} vs {max(hp, ap):.1f})."
    except (TypeError, ValueError):
        return ""
